import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <nav style={{ padding: "1rem", background: "#333", color: "#fff", fontSize: "1.2rem" }}>
        <Link href="/" style={{ marginRight: "2rem", color: "#fff", textDecoration: "none" }}>Home</Link>
        <Link href="/dashboard" style={{ color: "#fff", textDecoration: "none" }}>Dashboard</Link>
      </nav>
      <main style={{ padding: "2rem" }}>
        {children}
      </main>
    </body>
  </html>
);
}